FROM golang:1.17-alpine AS builder

WORKDIR /app

COPY ./ ./

RUN apk add --update --no-cache git
RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags "-s -w" -ldflags "-X main.version=${VERSION}" -o "dist/fourkeys_lambda" github.com/vimeda/fourkeys/cmd/lambda

# ---

FROM gcr.io/distroless/static

COPY --from=builder /app/dist/fourkeys_lambda /

ENTRYPOINT ["/fourkeys_lambda"]
